server:
  port: 8080
  version: 0.0.1-alpha
  servlet:
    session:
      timeout: 10m
spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 28750
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
      minimum-idle: 1
      maximum-pool-size: 3
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  session:
    store-type: redis
    redis:
      flush-mode: on_save
---
spring:
  redis:
    lettuce:
      pool:
        min-idle: 1
    host: localhost
    port: 6379
  profiles:
    active: local
hashids:
  salt: TestOAuth2
  length: 8
oauth2:
  codeStart: o/
  codeChar: "-"
domain: http://localhost:8080
